source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SFEmptyBackButton_Example', :exclusive => true do
  pod "SFEmptyBackButton", :path => "../"
end

target 'SFEmptyBackButton_Tests', :exclusive => true do
  pod "SFEmptyBackButton", :path => "../"

  
end
