osx_image: xcode7.2

language: objective-c
before_install:
- brew update || brew update
- brew install carthage
install:
- carthage bootstrap
script:
- set -o pipefail && xcodebuild analyze test -project SFEmptyBackButton.xcodeproj -sdk iphonesimulator -scheme SFEmptyBackButton -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
