language: objective-c
osx_image: xcode8.3

install:
- carthage update --platform iOS --no-use-binaries
script:
- set -o pipefail 
- xcodebuild -workspace SFEmptyBackButton.xcworkspace -scheme SFEmptyBackButton -destination "platform=iOS Simulator,name=iPhone 7" -enableCodeCoverage YES build-for-testing test-without-building | xcpretty
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
