language: objective-c
os: osx
osx_image: xcode7

install:
- gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet
- pod setup
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/SFEmptyBackButton.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint SFEmptyBackButton.podspec --quick

after_success:
  - bash <(curl -s https://codecov.io/bash)